server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.5.73:3306/muniubox?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: mysqlmuniubox

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,log4j,
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  config-location: "classpath:mybatis-config.xml"
  
#用户认证相关参数
authentication:
  expDate: 1800000
  secret: 201711090001
 
#上传图片相关路径 
userFileLogo:
  path: static/userfile/images/photo/logo
#初始密码
initPassword:
  password: Td*123456

projectPath:
  path: D\:\\workspaceold\\platformnet
 